### ISSUE TITLE
Fix Firefox Windows sidebar bug

### ISSUE THREAD

**Issue by juliedesmond** [atheycreek/atheycreek#28]
Tested on latest version on Chrome and no real issues noticed.  

Aesthetically, on a few of the pages the right sidebar extends way down the page and there is a large amount of white space to the left, which makes me feel unbalanced (Grade school page is a great example.)  It's that way on the current site, but the sidebar items on the new site seem a little larger, so it's even more pronounced.  Might consider seeing if things could be tightened up. Just an opinion though. 

I was also confused by the layout of the leadership page. 

Speaking of the leadership page - on my Android phone it runs off the left edge so you can't read the first new letters of the words. None of the other pages I looked at were off the screen, but they were right against the edge, which made readability a little difficult. The only other thing I noticed was the "Athey Creek" in the header drops a little below the header background and looks a little odd. 

I haven't gone through in Firefox in depth, but I did open it and notice there is a scroll bar on the right side but it doesn't scroll anywhere. 

I will try to test on IE and my iOS devices in the next few days.

**Comment by juliedesmond** [comment]
Here's a screenshot of what I'm seeing in Firefox on the right side. 

![firefox-accf](https://cloud.githubusercontent.com/assets/7938648/5601761/1d21d678-92cc-11e4-9653-71a79790877d.PNG)

**Comment by jdsimcoe** [comment]
@atheycreek/support Thanks Julie. Can you try to test this bug again? I pushed a change to fix another issue and it might have fixed this as well.

**Comment by juliedesmond** [comment]
No, the extra scroll bar in FIrefox is still there. :(

**Comment by jdsimcoe** [comment]
@atheycreek/support Can you reset cache in your browser and try to test one more time?

**Comment by juliedesmond** [comment]
This is fixed in Firefox now.
