### ISSUE TITLE
Building page 404 Error

### ISSUE THREAD

**Issue by rellimit** [atheycreek/atheycreek#29]
From the featured section on the main page -- building page doesn't exist.  Website looks good though - nice work.

![screen shot 2015-01-01 at 3 20 08 pm](https://cloud.githubusercontent.com/assets/7785169/5593559/4f1adb6e-91ca-11e4-90e7-2f9036eb68be.png)

**Comment by jdsimcoe** [comment]
@atheycreek/support I just fixed this! @davidfrost We need you to update the building page with stats ASAP showing that we raised all the `$$$`we needed to.

**Comment by davidfrost** [comment]
I just did this for now. Thanks!

[image1.PNG]

On Jan 1, 2015, at 3:31 PM, Jonathan Simcoe <notifications@github.com<mailto:notifications@github.com>> wrote:


@atheycreek/support<https://github.com/orgs/atheycreek/teams/support> I just fixed this! @davidfrost<https://github.com/davidfrost> We need you to update the building page with stats ASAP showing that we raised all the $$$we needed to.

**Comment by jdsimcoe** [comment]
Image didn't show up in GitHub.

**Comment by davidfrost** [comment]
http://atheycreek.com/about/building/

On Jan 1, 2015, at 3:50 PM, Jonathan Simcoe <notifications@github.com<mailto:notifications@github.com>> wrote:


Image didn't show up in GitHub.

**Comment by jdsimcoe** [comment]
:+1:
