### ISSUE TITLE
Build out an Athey worship album page

### ISSUE THREAD

**Issue by jdsimcoe** [atheycreek/atheycreek#32]
- [x] Upload final Light album files to SoundCloud
- [x] Create embed
- [x] Create graphics for page
- [x] Create descriptive text and album links
- [x] Link the newly created page to the Featured Slider

@atheycreek/owners 

From Brooke/Brett:

> My dad was wondering if you could look into having a link on the website for the worship record…maybe have “worship” as an option under “ministries” or something like that…he’d like to include ways people can get ahold of a physical copy of the album (which is essentially by calling the office or purchasing at church…) or a link to buy on iTunes. Would it be possible for you to look into that?

My proposal is that we upload the worship album to SoundCloud and make sure it is not able to be downloaded and use that as an embed on the newly created page to offer people a preview of the album.

Then we can also create links to download on iTunes, etc.

What do you guys think?

**Comment by jdsimcoe** [comment]
@atheycreek/owners @atheycreek/support The page is available for preview/review here:

http://atheycreek.com/ministries/worship/

Let me know when it is final and I will put it in the featured slider.

**Comment by rellimit** [comment]
Cool

Tim

On Jan 27, 2015, at 10:23, "Jonathan Simcoe" <notifications@github.com<mailto:notifications@github.com>> wrote:


@atheycreek/owners<https://github.com/orgs/atheycreek/teams/owners> @atheycreek/support<https://github.com/orgs/atheycreek/teams/support> The page is available for preview/review here:

http://atheycreek.com/ministries/worship/

Let me know when it is final and I will put it in the featured slider.

**Comment by jdsimcoe** [comment]
@atheycreek/owners Page is launched and linked to the Featured Slider.
