### ISSUE TITLE
Bible verses are not showing on Events page

### ISSUE THREAD

**Issue by k8rockwell** [atheycreek/atheycreek#33]
Hey Jonathan,
The bible verses are not showing up on the event pages.
Thanks, Kate

**Comment by jdsimcoe** [comment]
@k8rockwell I killed this feature when we moved to the new site. I don't know how critical it is to have Bible verses tied to events and we can put that in the events contents using a quote syntax if someone really wants it. Here is some Markdown for how to do quotations.

```md
> Direct trade listicle health goth, mumblecore normcore Austin retro McSweeney's vinyl Thundercats sriracha synth sustainable gentrify. Banh mi normcore paleo sustainable, wayfarers next level keffiyeh fanny pack vegan direct trade tousled bespoke cold-pressed retro tilde.
> —**1 Hipster 2:3**
```

And here is how it looks rendered:

> Direct trade listicle health goth, mumblecore normcore Austin retro McSweeney's vinyl Thundercats sriracha synth sustainable gentrify. Banh mi normcore paleo sustainable, wayfarers next level keffiyeh fanny pack vegan direct trade tousled bespoke cold-pressed retro tilde.
> —**1 Hipster 2:3**

I would put all Scriptures at the bottom of the event entry, so it closes out the post and doesn't distract from people wanting to get the main details.

@britchie555 What do you think?

**Comment by britchie555** [comment]
Sounds fine to me for now.  We can readdress later if needed.  Thx
