### ISSUE TITLE
Fix Teachings page default graphic

### ISSUE THREAD

**Issue by jdsimcoe** [atheycreek/atheycreek#44]
@davidfrost found that the default teaching graphic is broken:

http://atheycreek.com/teachings/6734/the-sin-cycle/

![screenshot](https://cloud.githubusercontent.com/assets/275617/6205519/6db4663e-b525-11e4-960d-4015a0531a26.png)

**Comment by jdsimcoe** [comment]
@atheycreek/support This is now fixed!

**Comment by britchie555** [comment]
Thx!
