### ISSUE TITLE
Broken Podcast Image on Homepage

### ISSUE THREAD

**Issue by juliedesmond** [atheycreek/atheycreek#48]
The audio podcast image on the homepage is broken.

**Comment by jdsimcoe** [comment]
@atheycreek/support Looks like it is working, today at least.

![screen shot 2015-03-23 at 11 05 51 am](https://cloud.githubusercontent.com/assets/275617/6786952/99a3c378-d14c-11e4-9dc9-5ecc997053fc.png)
