### ISSUE TITLE
Can't see dates in markdown/ event area

### ISSUE THREAD

**Issue by k8rockwell** [atheycreek/atheycreek#50]
![screenshot 2015-05-07 13 52 45](https://cloud.githubusercontent.com/assets/8239032/7525690/89cfcaf4-f4c0-11e4-8f71-387b832b42d3.png)

Jonathan,
I can't see the date/ calendar in the events area on symphony.  This has been like this for a while, but I'm hoping you can fix it so I don't break the website again.
Thank you!

**Comment by jdsimcoe** [comment]
@atheycreek/support Fixed.
