### ISSUE TITLE
Job Title Field

### ISSUE THREAD

**Issue by davidfrost** [atheycreek/atheycreek#51]
It doesn't appear that the "Job Title" field for members on the website are reflecting Symphony entries.

IE: See Judy Slaughter...

Symphony Entry ("Women's Ministry Director"): http://atheycreek.com/admin/publish/members/edit/12562/

Front-end Staff Page ("Staff"): http://atheycreek.com/about/staff/

Please let me know if you need more explanation. Thanks.

**Comment by jdsimcoe** [comment]
@davidfrost This is because these are driven by Members: Roles: http://atheycreek.com/admin/publish/members-roles/.

The `Role` setting determines what outputs on that page. We did this because the same people can play different roles (e.g. `Home Group Leader` and `Staff`, etc.) Hope that helps!

**Comment by davidfrost** [comment]
OK. Thanks.

On Jun 9, 2015, at 3:08 PM, Jonathan Simcoe <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidfrost<https://github.com/davidfrost> This is because these are driven by Members: Roles: http://atheycreek.com/admin/publish/members-roles/.

The Role setting determines what outputs on that page. We did this because the same people can play different roles (e.g. Home Group Leader and Staff, etc.) Hope that helps!
